export enum CATEGORIES_ACTION_TYPES {
	SET_CATEGORIES = "SET_CATEGORIES",
	FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START",
	FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS",
	FETCH_CATEGORIES_REJECTED = "FETCH_CATEGORIES_REJECTED",
}
